values updated for deployment
helxplatform/translator-devops pull request #151
Opened 2021-11-17 13:56 UTC by kannabhargav

2021-11-17 21:08 UTC, YaphetKG requested changes
- On automat/ncats-dev-valuesyaml, do we need to put all of what is defined in values-populate into ncats-dev values aswell ? reason i ask is as much as possible we would like to preserve the common values in a single file so changes can be tracked easily, and only put things we want to stricly override in the environments files (ncats-*-values.yaml) . 
- On cam kp , no need to specify NodePort on the values-populated.yaml , as the deployment script should use the values in ncats-dev yaml, when both of these files are passed. 

- More general question is there a reason we are converting to NodePort in the ITRB envronment ? 

(

2021-11-17 21:35 UTC, kannabhargav commented
- Yes we are using ncats-dev-valuesyaml as env specific whichever we have in the values file.
- NodePort has to be updated in ITRB env as we are using an alb ingress controller.

2021-11-18 15:56 UTC, YaphetKG commented
- please remove `app` section and its contents from automat/ncats-dev-values.yaml 
- remove `app` section from cam-kp-api/ncats-dev-values.yaml
- please change `service.type` in cam-kp-api/values-populated.yaml to `ClusterIP`, you already have `NodePort` Specified in cam-kp-api/ncats-dev-values.yaml so that would override it. No need to change it in values-populated
- please remove containerPort from questionRewrite ncats-dev-values.yaml. 

As a general rule, only keep variables that need have change in ncats-*-values.yaml files. 
Other variables that  don't need to change will always get picked up from values-populated.yaml or values.yaml in that order.

2021-11-18 16:06 UTC, YaphetKG approved these changes

2021-11-18 16:06 UTC, merged