Add environment variables to workflow runner
helxplatform/translator-devops pull request #230
Opened 2022-01-25 17:06 UTC by maximusunc

2022-01-26 16:24 UTC, YaphetKG requested changes
- In renci-dev-values-populated , seems like there is the ingress.class value set to translator , that would not work on sterling.

2022-01-26 18:14 UTC, maximusunc commented
The ingress class has been removed, and tls was added for public facing instance.

2022-01-26 19:05 UTC, PhillipsOwen approved these changes
looks good...

2022-01-27 14:54 UTC, YaphetKG approved these changes

2022-01-27 14:54 UTC, merged