Expose dev instances
helxplatform/translator-devops pull request #326
Opened 2022-03-15 14:17 UTC by maximusunc

Removed redundant ingress annotation code from services

2022-03-15 16:31 UTC, PhillipsOwen requested changes
the values.yaml files should only have values that are non-specific to the development or production product deployments.

2022-03-15 16:31 UTC, PhillipsOwen commented on helm/strider/values.yaml
> +  enabled: true
this definitely should not be here

2022-03-15 16:31 UTC, PhillipsOwen commented on helm/strider/values.yaml
> +  tls:
nor should this be here

2022-04-01 17:02 UTC, PhillipsOwen requested changes
see notes I left in slack

2022-04-06 13:09 UTC, PhillipsOwen requested changes
in answer coalesce dev values file: if ingress and TLS is enabled, and a cert-manger and a white-list values are specified then the server host name should be https://.  insure ncats meta.yaml has correct image/tag values.

in aragorn ranker dev/prod values files:  please review image tag values and note the differences.

in robokop-ara values files. replace pod security context with {} in values.yaml, other values files should have the real values.

in strider values file. xtrapi values indicate production settings. just blank them out and the the dev/prod values continue to be the real values.

2022-04-06 13:50 UTC, maximusunc commented
Made all requested changes. All the ncats image versions looked correct.

2022-04-06 14:11 UTC, merged